apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  destination:
    namespace: external-dns
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns
    chart: external-dns
    targetRevision: {{ .Values.externaldns.version }}
    helm:
      valuesObject:
        policy: sync
        sources:
          - ingress
          - gateway-httproute
        domainFilters:
        {{- range .Values.externaldns.dnsZones }}
          - "{{ . }}"
        {{- end }}  
        txtOwnerId: {{ .Values.cluster_name }}
        resources:
          limits:
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 64Mi
        serviceMonitor:
          enabled: true
          additionalLabels:
             release: kube-prometheus-stack
          
