apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-9"
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: core
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: {{ .Values.certmanager.version }}
    helm:
      valuesObject:
        crds:
          enabled: true
          keep: true
        namespace: "cert-manager"
        replicaCount: {{ .Values.certmanager.replicaCount }}
        securityContext:
          fsGroup: 1001
        serviceAccount:
          create: true
        enableCertificateOwnerRef: true
        resources:
          limits:
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 64Mi
        prometheus:
          servicemonitor:
            enabled: true
            labels:
              release: kube-prometheus-stack
