apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-route53
spec:
  acme:
    email: admin@vettom.online
    server: https://acme-v02.api.letsencrypt.org/directory   # Production service
    # server: https://acme-staging-v02.api.letsencrypt.org/directory   # Staging server
    privateKeySecretRef:
      name: letsencrypt-route53
    solvers:
    - selector:
        dnsZones:
          - vettom.online
          - "*.vettom.online"
      dns01:
        route53:
          region: eu-west-1s