
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: "{{ .Values.externalGateway.name }}-class"
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "10"
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: external-proxy-config
    namespace: envoy-gateway-system
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: "{{ .Values.externalGateway.name }}"
  namespace: "{{ .Values.externalGateway.namespace }}"
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "10"
    cert-manager.io/cluster-issuer: "{{ .Values.certManager.clusterIssuer }}"
spec:
  gatewayClassName: "{{ .Values.externalGateway.name }}-class"
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      hostname: "{{ .Values.externalGateway.hostname }}"
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            group: ""
            name: "{{ .Values.externalGateway.name }}-tls-cert"
            namespace: "{{ .Values.externalGateway.namespace }}"
