apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  sources:
  - repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: {{ .Values.argocd.version }}
    helm:
      valuesObject:
        global:
          domain: {{ .Values.argocd.argo_url_prefix }}.{{ .Values.domain }}
        server:
          extraArgs:
            - --insecure
          service:
            type: ClusterIP
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
              namespace: argocd
              additionalLabels:
                 release: kube-prometheus-stack
          httproute:
            enabled: true
            labels: {}
            annotations: {}
            parentRefs: 
              - name: external-gateway
                namespace: gateway
            hostnames: 
              - argocd.{{ .Values.domain }}
            rules:
              - matches:
                  - path:
                      type: PathPrefix
                      value: /              
        controller:
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
              namespace: argocd
              additionalLabels:
                 release: kube-prometheus-stack
        dex:
          enabled: false
        notifications:
          secret:
            create: false
          cm:
            create: false
